version: "3.5"

services:
  php_fpm:
    build: .
    container_name: cicd-test_php_fpm
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - php_cicd_test
    volumes:
    - ./:/var/www

  nginx:
    image: nginx:1.15
    container_name: cicd-test_nginx
    working_dir: /var/www
    networks:
      - php_cicd_test
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - ./:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  php_cicd_test: